repository: Haki-Malai/cv
url: hakimalai.com
version: 2

name: Haki Malai
title: Software Developer
email: hakimalai@outlook.com
phone: 6955065511

darkmode: true

github_username: Haki-Malai
linkedin_username: haki-malai
additional_links:
  - title: Pdf Download
    icon: far fa-file-pdf
    url: https://github.com/Haki-Malai/cv/raw/master/pdf/haki-malai-resume.pdf

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM_PLACEHOLDER"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

about_title: About
about_profile_image: images/profile.jpg
about_content: |
  Haki is a software engineer with a passion for problem-solving and continuous learning.
  Known for a curious and analytical mindset, he enjoys tackling challenges and finding innovative solutions, both in and out of work.
  He values collaboration and believes in the power of teamwork to achieve meaningful results. With a focus on personal growth,
  he strives to bring creativity, dedication, and a positive attitude to every project and interaction.
  Beyond his technical expertise, He finds balance in life through activities that stimulate both mind and body.


content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Hakra LTD
        sub_title: Full Stack Developer
        caption: May 2023 - Present
        description: |
            - Spearheads the redevelopment of the front-end for coinseats.com, enhancing SEO viability through advanced animations and design implementations based on designer templates, resulting in a 27% increase in organic traffic and a 14% boost in user engagement.
            - Hires and manages external contractors and freelancers for tasks such as UI/UX design, logo design, and content creation, ensuring cohesive and high-quality project deliverables.
            - Launched ticketparser.io, a comprehensive web application to facilitate event discovery and inventory synchronization from various third party sources, using Flask, React, and Docker to ensure scalability and maintainability. The platform reduced manual ticket parsing time by more than 90%
            - Implemented robust system architectures including CI/CD pipelines via GitHub Actions, and managed deployment on AWS ECS and S3 for backend and front-end scalability, cutting deployment times by 50% and ensuring 99.9% uptime.
            - Directs the development of section-mapper, an internal tool designed to aggregate and correlate data from multiple ticketing platforms using AI and NLP techniques for enhanced data accuracy and usability.
            - Enhances and maintains the manual pricer tool by refactoring legacy code to adhere to PEP8 standards, simplifying algorithms, and integrating new features to optimize ticket pricing strategies and market control.
            - Actively participates in daily standup meetings and followed Scrum methodology to ensure efficient project management and timely delivery of software milestones.
            - Collaborates closely with cross-functional teams to align development activities with business objectives and user requirements, fostering an agile and responsive development environment.

      - layout: right
        title: REMWS
        sub_title: Full Stack Developer
        caption: Oct. 2022 - May 2023
        link: remws.gr
        description: |
            - Developed new features to the mobile app by rewritting the existing .NET RESTful API using Python, resulting in a 30% reduction in API response time and enhancing overall app performance.
            - Used Apache Airflow ELT tool to synchronize the data of the ERP’s SQL Server database with the eshop’s MariaDB database, improving data synchronization efficiency and reducing data inconsistencies by 31%.
            - Improved code quality and performance by refactoring, debugging and testing existing codebase.
            - Led the development of the new React Native mobile application, from requirements gathering to deployment using Agile methodology.
            - Conducted code reviews and implemented a code quality checklist to ensure that all code contributions meet the company's standards and guidelines.
            - Optimized database queries and improves application performance by identifying and addressing bottlenecks and inefficiencies, which led to a 28% increase in query execution speed and a 22% reduction in server load.
            - Created and maintained technical documentation, including API specifications, user guides, and system architecture diagrams.

      - layout: left
        title: CONCISE TECHNOLOGIES LTD
        sub_title: Full Stack Developer
        caption: Sep. 2021 - Oct. 2022
        link: www.concise.gr
        description: |
            - Built several interactive and user-friendly advanced scientific calculators using modern web technologies such as JavaScript, HTML5, and CSS, focusing on writing maintainable, modular code and creating visually appealing UIs.
            - Designed and implemented a complete chat application using a full-stack approach, combining React Native, Flask, NoSQL, and websockets technologies, to provide users with real-time messaging and collaboration features.
            - Automated repetitive and manual tasks using scripting and tools (Python), saving significant time and effort for the team.
            - Developed and maintained a variety of web applications and services, using technologies such as Node.js, MongoDB and React, to deliver intuitive, responsive and secure solutions to end-users.

      - layout: right
        title: Freelance
        sub_title: Full Stack Developer
        caption: May 2021 - Sep. 2021
        description: |
            - Provided technical expertise and support to small local businesses, including developing e-commerce platforms, advising on technology needs and options, recommending deployment strategies, and offering IT services such as system setup and maintenance.
            - Leverage popular freelancing platforms, such as Upwork and Freelancer, to identify and secure clients, and delivered high-quality work on a variety of projects, including bug fixing, automation scripting with Python, and code module development. Successfully completed over 90% of projects ahead of schedule, leading to a 20% increase in repeat business.
            - Contributed to open-source projects and communities, sharing knowledge and best practices, and participating in code reviews and discussions.
            - Maintained effective communication channels with clients, providing regular progress updates, seeking feedback, and addressing any concerns or issues in a timely and professional manner.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Ionian University
        sub_title: BA in Informatics
        caption: 2017 - 2024
        quote: >
            Haki has completed all of his responsibilities and will officially graduate in late 2024.
        description: |
          Haki's graduation was extended due to his commitment to professional projects and a deeper exploration of advanced application techniques, enhancing both his academic and professional growth.
          In his thesis, Haki Malai develops a web application using modern software libraries and examines methods to ensure its reliable operation throughout the Software Development Life Cycle (SDLC).
          He employs unit tests and Static Application Security Testing (SAST) to detect errors and vulnerabilities. The research presents a Python-based RESTful API application, showcasing the use of HTML, CSS, and JavaScript with ReactJS.

  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: TicketParser
        link: https://ticketparser.io
        quote: >
          Internal registration required for full access.

        description: |
          Ticketparser.io is a robust web application developed to streamline event discovery and synchronize inventory from multiple third-party sources, achieving over a 90% reduction in manual ticket parsing time. The project leveraged Flask, React, and Docker to ensure scalability and maintainability, with CI/CD pipelines via GitHub Actions for efficient deployment on AWS ECS and S3, resulting in a 50% reduction in deployment times and 99.9% uptime. The front-end redevelopment focused on enhancing SEO and user engagement, leading to a 27% increase in organic traffic and a 14% boost in user interaction. The project also involved managing a team of external contractors for cohesive UI/UX design and content creation, and the development of tools to enhance data accuracy and pricing strategies, all within an agile, collaborative environment.

      - layout: left
        border: weak
        title: Arctic Fox
        link: https://arcticfox.herokuapp.com/
        link_text: Autogenerated OpenAPI documentation
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Haki-Malai/arctic-fox
        quote: >
          This is a part of Haki's thesis for his degree of the Ionian University.
        description: |
          The project employs the Flask framework to create a server architecture that manages HTTP requests and routes efficiently.
          It integrates extensions for data management, serialization, and cross-origin resource sharing.
          Features like asynchronous OAuth2 authentication, OpenAPI Swagger documentation, task management with Celery, email handling, and caching are included to enhance performance and functionality.
          The design emphasizes scalability and maintainability, catering to a variety of operational needs.

      - layout: left
        border: weak
        title: Arctic Fox UI
        link: http://arctic-fox-ui.s3-website-us-east-1.amazonaws.com
        link_text: AWS S3 Deploy
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Haki-Malai/arctic-fox-ui
        quote: >
          Requires invitation to be able to login, please use the contact details to request one.
        description: |
          The project is a well-structured user interface framework using ReactJS, designed for efficient management of files, folders, and user interactions. It features robust state management and seamless server communication through a dedicated API client, focusing on modularity and ease of use. This setup ensures the framework is both maintainable and scalable, supporting modern web application development.

      - layout: left
        border: weak
        title: digital-odyssey
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Haki-Malai/digital-odyssey
        quote: >
        description: |
          A custom e-commerce shop inspired by opencart and based on the codebase of https://petshoppotamos.gr. The project includes a CMS and typical ecommerce features such as product catalog management, shopping cart functionality, and payment integration.

      - layout: left
        border: weak
        title: TriviaMaster
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Haki-Malai/flask-triviamaster
        quote: >

        description: |
          A trivia game in Python that uses SQLAlchemy for the database operations and includes automated scripts via API, shell operations and database migrations.

      - layout: left
        border: weak
        title: Potamos Pet Shop
        link: https://petshoppotamos.gr
        quote: >
          The website is temporarily offline.
        description: |
          Except of what is visible to the customer, there also exists an admin page that gives access to the owner to update the website with new products, change the colors, add art, promote new products/sales and much more! The website is build with Flask and uses Jinja2 for the frontend. The goal for the future is to make it faster by making the website static instead of dynamic, with the price of having to wait a little more to be able to see any changes from the client view.

      - layout: left
        border: weak
        title: pacman.js
        link: https://newpacmanjs.netlify.app/
        link_text: Netlify Demo
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Haki-Malai/pacman.js/
        description: |
          A unique variant of the classic Pac-Man with the goal of getting his first steps into JavaScript. The final product is quite impressive, having in mind there were no third party libraries involved, this was Haki's first time I ever used HTML, CSS and JavaScript and most of the art was drawn by me!
          After a while I decided to rebuild the project with a library called "Phaser" and the result was much smoother but I couldn't finish the project because of other duties.
          There are two demos, the old and the new versions, that can be tried in your browse and they are linked in the GitHub Repository!

      - layout: left
        border: weak
        title: JavaScript Games
        link: https://github.com/Haki-Malai/Games/
        link_text: GitHub Repository
        additional_links:
          - title: Netlify Demo Tetris
            icon: fas fa-th-large
            url: https://tetris-hm.netlify.app/
          - title: Netlify Demo Pac-Man Old
            icon: fas fa-ghost
            url: https://oldpacman.netlify.app/
          - title: Netlify Demo SudokuX
            icon: fas fa-th
            url: https://sudokux.netlify.app/
          - title: Netlify Demo Hyper Sudoku
            icon: fas fa-th
        description: |
          A unique variant of the classic Pac-Man with the goal of getting his first steps into JavaScript. The final product is quite impressive, having in mind there were no third party libraries involved, this was Haki's first time I ever used HTML, CSS and JavaScript and most of the art was drawn by me!
          After a while I decided to rebuild the project with a library called "Phaser" and the result was much smoother but I couldn't finish the project because of other duties.
          There are two demos, the old and the new versions, that can be tried in your browse and they are linked in the GitHub Repository!

  - title: Hobbies and Interests
    layout: text
    content: |
      Some of Haki's hobbies and interests include:
      - Chess
      - Farming
      - Martial Arts
      - Motorbikes
      - Jumping Rope
      - Fantasy Novels
      - Drawing
      - Spirituality
      - Lifting Weights


footer_show_references: true
references_title: References on request

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
