# Site
repository: Haki-Malai/cv
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Haki Malai
title: Software Developer
email: hakimalai@outlook.com
#email_title: Work-Email (Email title override)
phone: 6944873194
# phone_title: Phone (Phone title override)
#website: 
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: jekyllrb
github_username: Haki-Malai
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: haki-malai
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
  - title: Pdf Download
    icon: far fa-file-pdf
    url: https://github.com/Haki-Malai/cv/raw/master/pdf/haki-malai-resume.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Haki and I was born in Corinth, Greece. I have an innate love for computers and love exploring new technologies. Right now I am exploring the depths of the website world. To be more precise, I am mastering the languages of JavaScript and Python, from which I love using the open source libraries “Flask” and “React/React-Native”. I am also into cloud based deployment, traditional server deployments, docker containers, WSGI servers, server security, RESTful APIs, optimizing the software development cycle and more, you get the idea…
  At the moment, I am finishing my thesis for my informatics degree in Ionian University that's about basically everything I like: a React-Native app that communicates with a gunicorn served API server and a lot more cool stuff!

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Pet Shop
        link: https://petshoppotamos.gr
        link_text: Heroku Deploy
        quote: >
          This is a website for a very friendly pet shop based in Corfu, Potamos. 
        description: | # this will include new lines to allow paragraphs
          Except of what is visible to the customer, there also exists an admin page that gives access to the owner to update the website with new products, change the colors, add art, promote new products/sales and much more! The website is build with Flask and uses Jinja2 for the frontend. My goal for the future is to make it faster by making the website static instead of dynamic, with the price of having to wait a little more to be able to see any changes from the client view.
        
      - layout: left
        border: weak
        title: Arctic Fox
        link: https://arcticfox.herokuapp.com/
        link_text: Autogenerated OpenAPI documentation
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Haki-Malai/arctic-fox
        quote: >
          This is a part of my ongoing thesis
        description: |
          An implementation that uses python's Flask web framework to create an OpenAPI and auto generate it's spec file and documentation page.
          Unittests, SAST, DAST and CI/CD tools were used for automated testing and locating security and error prone flaws.
      
      - layout: left
        border: weak
        title: Arctic Fox UI
        link: https://arcticfoxweb.netlify.app/
        link_text: Netlify Login Demo
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Haki-Malai/arctic-fox
        quote: >
          For demonstration puproses, the user input is sanitished throught the server.
        description: |
          A simple UI has also been developed with React-Native that means it's fully compatible with Android and iOS and ready to be deployed into an app with the same codebase.
       
      - layout: left
        border: weak
        title: URL Shortener
        link: https://url-shortener-hm.netlify.app
        link_text: Netlify Demo
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Haki-Malai/url-shortener
        quote: >
          Slow speeds as it uses heroku and firebase for free.
        description: |
          This project had the aim of learning about deploying simple apps for free and to demonstrate my skill set. Of course, the speed is slow because Heroku puts free dynos on idle mode.
          Node JS for the backend Heroku deployment.
          React JS for Netlify frontend demo.
          Firebase for storing the data.

      - layout: left
        border: weak
        title: pacman.js
        link: https://newpacmanjs.netlify.app/
        link_text: Netlify Demo
        additional_links:
          - title:  Github page for project
            icon: fab fa-github
            url: https://github.com/Haki-Malai/pacman.js/
        description: |
          A unique variant of the classic Pac-Man with the goal of getting my first steps into JavaScript. The final product is quite impressive, having in mind there were no third party libraries involved, this was my first time I ever used HTML, CSS and JavaScript and most of the art was drawn by me!
          After a while I decided to rebuild the project with a library called "Phaser" and the result was much smoother but I couldn't finish the project because of other duties.
          There are two demos, the old and the new versions, that can be tried in your browse and they are linked in the GitHub Repository!

      - layout: left
        border: weak
        title: JavaScript Games
        link: https://github.com/Haki-Malai/Games/
        link_text: GitHub Repository
        additional_links:
          - title: Netlify Demo Tetris
            icon: fas fa-th-large
            url: https://tetris-hm.netlify.app/
          - title: Netlify Demo Pac-Man Old
            icon: fas fa-ghost
            url: https://pacmanold.netlify.app/
          - title: Netlify Demo SudokuX
            icon: fas fa-th
            url: https://sudokux.netlify.app/
          - title: Netlify Demo Hyper Sudoku
            icon: fas fa-th
        description: |
          A unique variant of the classic Pac-Man with the goal of getting my first steps into JavaScript. The final product is quite impressive, having in mind there were no third party libraries involved, this was my first time I ever used HTML, CSS and JavaScript and most of the art was drawn by me!
          After a while I decided to rebuild the project with a library called "Phaser" and the result was much smoother but I couldn't finish the project because of other duties.
          There are two demos, the old and the new versions, that can be tried in your browse and they are linked in the GitHub Repository!
          
        
          
          
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
